/*
 * bitnet-lut-kernels.h — Lookup-table GEMM kernel stubs
 *
 * This file is normally generated by:
 *   python utils/codegen_tl1.py  (ARM64 TL1 kernels)
 *   python utils/codegen_tl2.py  (x86_64 TL2 kernels)
 *
 * Or automatically via:
 *   python setup_env.py -md <model_dir> -q tl1
 *   python setup_env.py -md <model_dir> -q tl2
 *
 * This stub allows cmake to configure and build with I2_S kernels (default)
 * without running codegen first.  TL1/TL2 functionality is disabled when
 * neither GGML_BITNET_ARM_TL1 nor GGML_BITNET_X86_TL2 is defined.
 */

#pragma once

#if defined(GGML_BITNET_ARM_TL1)
#error "TL1 kernels not generated yet. Run: python utils/codegen_tl1.py"
#endif

#if defined(GGML_BITNET_X86_TL2)
#error "TL2 kernels not generated yet. Run: python utils/codegen_tl2.py"
#endif
