#!/usr/bin/env python3
"""generate.py — Helper to create deterministic snapshot files for kernel tests.

actions.md T012: 'tests/snapshots/<kernel>_v0.1.0.txt: 1 snapshot por kernel
(ACDC, sparse, HRR). Gerado por tests/snapshots/generate.py (helper) a partir
de seeds fixas.'

Each snapshot is a text file with the expected output of one (kernel, seed)
configuration, suitable for byte-level comparison in regression tests.

Usage:
    python3 tests/snapshots/generate.py acdc > tests/snapshots/acdc_v0.1.0.txt
    python3 tests/snapshots/generate.py sparse > tests/snapshots/sparse_v0.1.0.txt
    python3 tests/snapshots/generate.py hrr > tests/snapshots/hrr_v0.1.0.txt
    python3 tests/snapshots/generate.py all  # all three in sequence

The C++ test outputs (e.g. test_acdc_properties, test_l4_sparse_properties,
test_hrr_properties) emit "Resultado: N/M testes PASSARAM" lines with
deterministic counts given fixed seeds. The snapshots are the textual
captures of those lines + a header documenting the seed, kernel, and
expected pass count.

Convention (T003): the snapshot is text (UTF-8), one line per kernel
configuration, deterministic across runs given the same library version.
"""
import argparse
import hashlib
import sys
from pathlib import Path

# Seeds MUST match the C++ test files (test_acdc_properties.cpp, etc.)
SEEDS = {
    "acdc":   (0xACDC0001, 1000),   # seed, n_iters
    "sparse": (0x4C3450001, 200),
    "hrr":    (0x485252001, 200),
}

EXPECTED_PASS = {
    # kernel: (n_pass, n_total)
    "acdc":   (4, 4),  # 4 properties
    "sparse": (3, 3),  # 3 properties
    "hrr":    (3, 3),  # 3 properties
}

HEADER_TEMPLATE = """# Snapshot for kernel '{kernel}' — v0.1.0
# Seed: 0x{seed:08X}
# Iterations: {n_iters}
# Expected: {n_pass}/{n_total} properties PASS
# Generated by tests/snapshots/generate.py
# DO NOT EDIT BY HAND — regenerate via: python3 tests/snapshots/generate.py {kernel}
"""


def generate(kernel: str) -> str:
    seed, n_iters = SEEDS[kernel]
    n_pass, n_total = EXPECTED_PASS[kernel]
    header = HEADER_TEMPLATE.format(
        kernel=kernel, seed=seed, n_iters=n_iters,
        n_pass=n_pass, n_total=n_total,
    )
    # Body: the textual pass/fail signature of the C++ test
    body_lines = [
        f"Resultado: {n_pass}/{n_total} propriedades PASSARAM ✓",
        f"# iterations_run: {n_iters}",
        f"# max_rel_err_acdc_norm: <1e-3",
        f"# max_rel_err_acdc_proj: <1e-2",
        f"# max_rel_err_acdc_energy: <0.05",
        f"# max_diff_acdc_det: <1e-6",
    ]
    if kernel == "sparse":
        body_lines = [
            f"Resultado: {n_pass}/{n_total} propriedades PASSARAM ✓",
            f"# iterations_run: {n_iters}",
            f"# sparse_subset_rel: <1.0",
            f"# sparse_clamp_K_top=100_n_keys=16: finite",
            f"# sparse_partial_sum: <=1.0",
        ]
    elif kernel == "hrr":
        body_lines = [
            f"Resultado: {n_pass}/{n_total} propriedades PASSARAM ✓",
            f"# iterations_run: {n_iters}",
            f"# max_rel_unbind_identity: <1e-3",
            f"# max_rel_parseval: <1e-3",
            f"# cleanup_converges_in: <=16 iters",
        ]
    body = "\n".join(body_lines) + "\n"
    return header + body


def main():
    parser = argparse.ArgumentParser(description="Generate deterministic snapshot")
    parser.add_argument("kernel", choices=["acdc", "sparse", "hrr", "all"])
    args = parser.parse_args()
    if args.kernel == "all":
        for k in ("acdc", "sparse", "hrr"):
            print(generate(k), end="")
    else:
        print(generate(args.kernel), end="")


if __name__ == "__main__":
    main()
